// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoEQ57F6QctjtqtpSjxKjzIjESHFfXeJE',
    appId: '1:638145567351:web:a797e5960479c1eb0b4472',
    messagingSenderId: '638145567351',
    projectId: 'kscan-c620d',
    authDomain: 'kscan-c620d.firebaseapp.com',
    storageBucket: 'kscan-c620d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiUlQSS8uBcGbT2OZ3wKuodcC-d6eLcvw',
    appId: '1:638145567351:android:f7a8188b374776490b4472',
    messagingSenderId: '638145567351',
    projectId: 'kscan-c620d',
    storageBucket: 'kscan-c620d.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCoEQ57F6QctjtqtpSjxKjzIjESHFfXeJE',
    appId: '1:638145567351:web:4f4fe922359b85520b4472',
    messagingSenderId: '638145567351',
    projectId: 'kscan-c620d',
    authDomain: 'kscan-c620d.firebaseapp.com',
    storageBucket: 'kscan-c620d.firebasestorage.app',
  );
}
